export const GET_REQUEST = "GET_REQUEST";
export const GET_FAILURE = "GET_FAILURE";

export const GET_SIGNIN_SUCCESS = "GET_SIGNIN_SUCCESS";

export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";

export const ALREADY_LOGGED_IN = "ALREADY_LOGGED_IN"

export const GET_ALL_DATA_SUCCESS =  "GET_ALL_DATA_SUCCESS"
